### ISSUE TITLE
Cannot validate request with no content-type if body is not required.

### ISSUE THREAD

**Issue by fabiohecht** [openapi4j/openapi4j#119]
**Describe the bug**
Request validator does not properly handle `requestBody` with `required: false`.

**To Reproduce**

1. Schema has an optional body:
```
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/whatever'
      required: false
```

2. Try and validate request with no body (thus no Content-Type header).

3. ValidationException is thrown:
```
Invalid request.
Validation error(s) :
Content type 'null' is not allowed for body content. (code: 203)
```

**Expected behavior**
No exception thrown.

**Comment by llfbandit** [comment]
If required field is omitted, does it work?

**Comment by fabiohecht** [comment]
If there is a content-type header, then validation works. However, it should work with no header and no body.

**Comment by llfbandit** [comment]
This should be fixed in 1.0.3-SNAPSHOT.

Are you able to validate the changes ?

**Comment by fabiohecht** [comment]
Hi! I just tested with 1.0.5 and the issue is still present. I have a POST with an optional body that only works without a body if content-type header is set. Thanks for looking into this!
