### ISSUE TITLE
int64 or int32 format not identified by openapi4j tool

### ISSUE THREAD

**Issue by kbora123** [openapi4j/openapi4j#152]
**Version**  
1.0.2  

**Describe the bug**  
int64 or int32 format not identified by openapi4j tool

            "properties": {
              "request_depth": {
                "maximum": 9007199254740992,
                "default": 9007199254740992,                
                "minimum": -1,
                "type": "integer",
                "format": "int64"
              }
 
I get the below error when openapi4j is used for validation

paths./model_to_review.put.requestBody.content.application/json.schema.properties.model_to_review.properties.instances.properties.data.properties.request_depth.default: Value '9007199254740992' is incompatible with schema type 'integer' (code: 138)
From: paths./model_to_review.put.requestBody.content.application/json.schema.properties.model_to_review.properties.instances.properties.data.properties.request_depth.default
components.schemas.HTTPInspectInstanceObject.properties.data.properties.request_depth.default: Value '9007199254740992' is incompatible with schema type 'integer' (code: 138)
From: components.schemas.HTTPInspectInstanceObject.properties.data.properties.request_depth.default

Sample Code:
        OpenApi3 openAPI = new OpenApi3Parser().parse(new File(openAPISpecPath), false);
        
       // Explicit validation of the API spec
        ValidationResults results = OpenApi3Validator.instance().validate(openAPI);

**Expected behavior**  
The above schema error should not be given.  

**Additional context**  

**To Reproduce**  
1. ...
2. ...
3. ...  

**Reproducer**  
Please fill a reproducer for debugging purpose.

**Comment by llfbandit** [comment]
Hi and welcome,

The issue is located in parser module.
The default value isn't checked with 'format' keyword, so 'integer' type is always checked... against Integer.

As a workaround, you can remove or lower your default value for now.

**Comment by llfbandit** [comment]
Fixed with d947c59

**Comment by kbora123** [comment]
I still see error with 1.0.5 version. The sample schema file contents is given below.

"max_resp_len": {
				"minimum": 0,
				"type": "integer",
				"format": "int64",
				"description": "maximum FTP response accepted by client",
				"maximum": 4294967295,
				"default": 4294967295
}

Error
-------

Validation error(s) :
paths./f_client.put.requestBody.content.application/json.schema.properties.instances.properties.data.properties.max_resp_len.default: Value '4294967295' is incompatible with schema type 'integer' (code: 138)
From: paths./f_client.put.requestBody.content.application/json.schema.properties.instances.properties.data.properties.max_resp_len.default
components.schemas.f_client.max_resp_len.default: Value '4294967295' is incompatible with schema type 'integer' (code: 138)
From: components.schemas.f_client_snort.max_resp_len.default

	at org.openapi4j.parser.validation.v3.OpenApi3Validator.validate(OpenApi3Validator.java:28)
	at com.cisco.api.external.rest.docs.OpenAPI4jValidationPOCEntireContents.main(OpenAPI4jValidationPOCEntireContents.java:45)
